identity = "1d591e9b257e8fe5f5d1c9845e8474778d28a304"
resolved_url = "https://www.philschmid.de/rss"
title = "philschmid.de - RSS feed"
site_url = "https://www.philschmid.de/"
body_hash = "e0bc96fdc7713085c69cb16b7c5805ba352a9091"
