identity = "5e7cf4436fafe7f5e16b3a7d9177507c02980a59"
resolved_url = "https://lobste.rs/top/1w.rss"
title = "Lobsters: Top Stories of the Past Week"
site_url = "https://lobste.rs/"
etag = '"dlu887cbss5lbxk-gzip"'
last_modified = "Fri, 02 Oct 2026 08:58:07 GMT"
body_hash = "a4c54d79cda2bb085df0fba29013801d90ab21a8"
