identity = "5e7cf4436fafe7f5e16b3a7d9177507c02980a59"
resolved_url = "https://lobste.rs/top/1w.rss"
title = "Lobsters: Top Stories of the Past Week"
site_url = "https://lobste.rs/"
etag = '"dlwsukk4097mvhz-gzip"'
last_modified = "Mon, 05 Oct 2026 09:33:02 GMT"
body_hash = "643526a0bb4f7f2a11e2112d11c131544ca253fe"
