identity = "5e7cf4436fafe7f5e16b3a7d9177507c02980a59"
resolved_url = "https://lobste.rs/top/1w.rss"
title = "Lobsters: Top Stories of the Past Week"
site_url = "https://lobste.rs/"
etag = '"dlr1szfmml9gbri-gzip"'
last_modified = "Mon, 28 Sep 2026 15:18:08 GMT"
body_hash = "bb9ae7434b55192eab8570d2c15d2c1229fc8a53"
