identity = "fa89c3714661dd428af5d15531129704bcceaa7b"
resolved_url = "https://martinfowler.com/feed.atom"
title = "Martin Fowler"
site_url = "https://martinfowler.com/"
etag = '"2aa9f-65c9f71cbc8c0"'
last_modified = "Tue, 29 Sep 2026 13:48:59 GMT"
body_hash = "8960d2f91cc75e20a01fd04e7699a64d2b866e6c"
