identity = "fa89c3714661dd428af5d15531129704bcceaa7b"
resolved_url = "https://martinfowler.com/feed.atom"
title = "Martin Fowler"
site_url = "https://martinfowler.com/"
etag = '"2ab60-65cb3ecdbe7c0"'
last_modified = "Wed, 30 Sep 2026 14:15:03 GMT"
body_hash = "e8c0ac3bb53e51fd15f5d1c7a399197f7c3de7c7"
