identity = "05fd7c0ed74b4df973b30e9a0e92cc9ad4369783"
resolved_url = "https://slack-status.com/feed/atom"
title = "Slack System Status"
site_url = "https://slack-status.com/"
language = "en-US"
body_hash = "54a5d808e724eddd084c2fe79f75213098b1b4e9"
