identity = "97378c43881f00f6a855fc7b587b67fc28067db3"
resolved_url = "https://nicholas.carlini.com/writing/feed.xml"
title = "Nicholas Carlini"
site_url = "https://nicholas.carlini.com/"
etag = 'W/"69aeef32-5a34"'
last_modified = "Mon, 09 Mar 2026 16:02:58 GMT"
body_hash = "7dfdd746b1dd2b07052bd227476f783bf1213669"
