identity = "49cc7c99f624dab263cb314a721ca6464e55e249"
resolved_url = "https://huggingface.co/blog/feed.xml"
title = "Hugging Face - Blog"
site_url = "https://huggingface.co/blog"
language = "en-US"
etag = 'W/"3f12f-kB2gnDRdtuXL9ZzR7B0ltLypmfQ"'
body_hash = "901da09c345db6e5cbf59cd1ec1d25b4bca999f4"
