identity = "49cc7c99f624dab263cb314a721ca6464e55e249"
resolved_url = "https://huggingface.co/blog/feed.xml"
title = "Hugging Face - Blog"
site_url = "https://huggingface.co/blog"
language = "en-US"
etag = 'W/"3eb60-7smxbYDpaIn3sXs66OUT2ey2K+4"'
body_hash = "eec9b16d80e96889f7b17b3ae8e513d9ecb62bee"
