identity = "49cc7c99f624dab263cb314a721ca6464e55e249"
resolved_url = "https://huggingface.co/blog/feed.xml"
title = "Hugging Face - Blog"
site_url = "https://huggingface.co/blog"
language = "en-US"
etag = 'W/"3ec98-ZyrJO6p4xnkH8tzPSYyutpc7oGk"'
body_hash = "672ac93baa78c67907f2dccf498caeb6973ba069"
