identity = "b4a8a36abc52a388c779d7523c8610e1d591470e"
resolved_url = "https://world.hey.com/dhh/feed.atom"
title = "David Heinemeier Hansson"
site_url = "https://world.hey.com/dhh"
language = "en-US"
etag = 'W/"44fcb7263a7587d9ba0b13070e6980ce"'
body_hash = "6b6526acc6be42a55d453ce3d630aa87cf45e48b"
