identity = "b4a8a36abc52a388c779d7523c8610e1d591470e"
resolved_url = "https://world.hey.com/dhh/feed.atom"
title = "David Heinemeier Hansson"
site_url = "https://world.hey.com/dhh"
language = "en-US"
etag = 'W/"7297b7672a755bcd15341a36bf5465bf"'
body_hash = "cf67a86d652c60cc2a50c49f5decdf2148c70622"
