identity = "b4a8a36abc52a388c779d7523c8610e1d591470e"
resolved_url = "https://world.hey.com/dhh/feed.atom"
title = "David Heinemeier Hansson"
site_url = "https://world.hey.com/dhh"
language = "en-US"
etag = 'W/"37ef2cc329bd0ecad7f3f4c69304694f"'
body_hash = "aadfd007eec4bb1a730cf95e09a19ad1191416a5"
