identity = "da915a6e48f2656e02f5ed28995ffc291acac6cd"
resolved_url = "https://feeds.acast.com/public/shows/le-rdv-tech"
title = "Le rendez-vous Tech - RDV Tech"
site_url = "https://www.rdvtech.fr/"
language = "fr"
etag = 'W/"djEuMi4wOjE3OTA2OTA0Mzk1NTk="'
body_hash = "0af71b99e36fb876d2e3d978d4728de5e2b0f7c4"
