identity = "da915a6e48f2656e02f5ed28995ffc291acac6cd"
resolved_url = "https://feeds.acast.com/public/shows/le-rdv-tech"
title = "Le rendez-vous Tech - RDV Tech"
site_url = "https://www.rdvtech.fr/"
language = "fr"
etag = 'W/"djEuMi4wOjE3OTEyOTcwMzkyNjg="'
body_hash = "add395bd04ac234f0905299f343d685edeb2dd6d"
