identity = "ba7c57f6944bccf3ca7da7e6ff2845dd16aa9eaf"
resolved_url = "https://lucumr.pocoo.org/feed.atom"
title = "Armin Ronacher's Thoughts and Writings"
site_url = "https://lucumr.pocoo.org/"
etag = 'W/"6abc3073-2ff3e"'
last_modified = "Tue, 29 Sep 2026 21:41:07 GMT"
body_hash = "52cf1f266d302a8ef5f8ee7c1ea68a8a9e6dc8ec"
