identity = "ba7c57f6944bccf3ca7da7e6ff2845dd16aa9eaf"
resolved_url = "https://lucumr.pocoo.org/feed.atom"
title = "Armin Ronacher's Thoughts and Writings"
site_url = "https://lucumr.pocoo.org/"
etag = 'W/"6ac20823-2ff3e"'
last_modified = "Sun, 04 Oct 2026 08:02:43 GMT"
body_hash = "eb491ed447cdc0890397f9fc3d6627d6824f1bc2"
