identity = "79b32c4202bded4b55d8ae74bc41729d0a5b0811"
resolved_url = "https://www.anthropic.com/news"
title = 'Newsroom \ Anthropic'
site_url = "https://www.anthropic.com/"
language = "en"
body_hash = "c1ae9cd8a7e83fac2c4217c73d8f36474066cad4"
