identity = "79b32c4202bded4b55d8ae74bc41729d0a5b0811"
resolved_url = "https://www.anthropic.com/news"
title = 'Newsroom \ Anthropic'
site_url = "https://www.anthropic.com/"
language = "en"
body_hash = "474177b138b975a55531b99080ed436a3e91b0fa"
