identity = "0dcb8a3e3f36d53222ffe087fb74ec66656eba4c"
resolved_url = "https://ampcode.com/news.rss"
title = "Amp News"
site_url = "https://ampcode.com/news"
etag = '"66712c02bc79c4b017834cf5e1bd5bf4"'
body_hash = "f79f02e4d444bfbba8cd28e3ebacf297d0a73299"
