identity = "5096dc08b83a82a8ec364e2b44c3cfc4a2098d41"
resolved_url = "https://newsletter.pragmaticengineer.com/feed"
title = "The Pragmatic Engineer"
site_url = "https://newsletter.pragmaticengineer.com/"
language = "en"
etag = 'W/"88163-HrTgDymPLhj4Urtg2snrvWS5WCQ"'
body_hash = "1eb4e00f298f2e18f852bb60dac9ebbd64b95824"
