identity = "5096dc08b83a82a8ec364e2b44c3cfc4a2098d41"
resolved_url = "https://newsletter.pragmaticengineer.com/feed"
title = "The Pragmatic Engineer"
site_url = "https://newsletter.pragmaticengineer.com/"
language = "en"
etag = 'W/"88163-6nwiQ8ScClDd5jlZksty8xoB+zM"'
body_hash = "ea7c2243c49c0a50dde6395992cb72f31a01fb33"
