identity = "5096dc08b83a82a8ec364e2b44c3cfc4a2098d41"
resolved_url = "https://newsletter.pragmaticengineer.com/feed"
title = "The Pragmatic Engineer"
site_url = "https://newsletter.pragmaticengineer.com/"
language = "en"
etag = 'W/"92d80-KZf8/k5glq0AEvlrGLxqAQsioFA"'
body_hash = "2997fcfe4e6096ad0012f96b18bc6a010b22a050"
