identity = "e57339d2da55f99410e3770305dae0de99354bcc"
resolved_url = "https://geohot.github.io//blog/feed.xml"
title = "the singularity is nearer"
site_url = "https://geohot.github.io//blog/"
etag = 'W/"6ac1e56b-9f30"'
last_modified = "Sun, 04 Oct 2026 05:34:35 GMT"
body_hash = "e64661825c2e279b31e3e989da6f621232875273"
