identity = "e57339d2da55f99410e3770305dae0de99354bcc"
resolved_url = "https://geohot.github.io//blog/feed.xml"
title = "the singularity is nearer"
site_url = "https://geohot.github.io//blog/"
etag = 'W/"6ac9c1a0-957d"'
last_modified = "Sat, 10 Oct 2026 04:40:00 GMT"
body_hash = "c4c630f0b35922cb8d7bb7692c2a063173612fc1"
