identity = "e57339d2da55f99410e3770305dae0de99354bcc"
resolved_url = "https://geohot.github.io//blog/feed.xml"
title = "the singularity is nearer"
site_url = "https://geohot.github.io//blog/"
etag = 'W/"6abde4c1-9f26"'
last_modified = "Thu, 01 Oct 2026 04:42:41 GMT"
body_hash = "a12a8fc733c70eae6245d06b33a283c3cc1e8399"
