identity = "5e7cf4436fafe7f5e16b3a7d9177507c02980a59"
resolved_url = "https://lobste.rs/top/1w.rss"
title = "Lobsters: Top Stories of the Past Week"
site_url = "https://lobste.rs/"
etag = '"dlqc7uwrw5mabo2-gzip"'
last_modified = "Sun, 27 Sep 2026 19:15:05 GMT"
body_hash = "fc4d6a43555b59b312932f1eaef16db4405c1863"
