identity = "2c0d78b648bd40de13eb7fdcbf56bd9515d3eb2f"
resolved_url = "https://www.computerenhance.com/feed"
title = "Computer, Enhance!"
site_url = "https://www.computerenhance.com/"
language = "en"
etag = 'W/"1aca7-oXRy0zn5AlELgGIF9hj0EZbgB30"'
body_hash = "a17472d339f902510b806205f618f41196e0077d"
