identity = "2c0d78b648bd40de13eb7fdcbf56bd9515d3eb2f"
resolved_url = "https://www.computerenhance.com/feed"
title = "Computer, Enhance!"
site_url = "https://www.computerenhance.com/"
language = "en"
etag = 'W/"1a9af-MEZmpx3We5KWPNMfLyH/GS+nxDc"'
body_hash = "304666a71dd67b92963cd31f2f21ff192fa7c437"
