identity = "68c13618454cdaa6e42f3c6e8b0e5812343f31c0"
resolved_url = "https://karpathy.bearblog.dev/feed/"
title = "karpathy"
site_url = "https://karpathy.bearblog.dev/"
last_modified = "Sun, 27 Sep 2026 12:46:05 GMT"
body_hash = "d18c5f1457a0a6e22db05d80f862c69a345c8cf9"
