identity = "3efda69b7f4006f1d1ec205a2dfb35a00357a341"
resolved_url = "https://steve-yegge.medium.com/feed"
title = "Stories by Steve Yegge on Medium"
site_url = "https://medium.com/@steve-yegge"
body_hash = "909c057e4fd4c4aad373aeb6c22d6a74154c9bed"
