identity = "19a1fe166ef0b5802c1e4f16de7ec08e92962aa1"
resolved_url = "https://borischerny.com/feed.xml"
title = "Boris Cherny’s Blog"
site_url = "https://borischerny.com/"
etag = 'W/"6aaf2fc3-13525"'
last_modified = "Sun, 20 Sep 2026 00:58:43 GMT"
body_hash = "d08cb4b4f28c7004e4b3ffa5e502d0b9873b6f8e"
