identity = "1b20e3cefa53bb537c9111573807259bb431178f"
resolved_url = "https://blog.google/innovation-and-ai/technology/ai/rss/"
title = "AI"
site_url = "https://blog.google/innovation-and-ai/technology/ai/"
language = "en-US"
body_hash = "dbccf9fa43feac7a5cd03c1819759e0a8b185b34"
