identity = "1b20e3cefa53bb537c9111573807259bb431178f"
resolved_url = "https://blog.google/innovation-and-ai/technology/ai/rss/"
title = "AI"
site_url = "https://blog.google/innovation-and-ai/technology/ai/"
language = "en-US"
body_hash = "6d718a73574d7cf42ba5756a4945247c2066c1a6"
