identity = "5d1283f7a9c2743451bb5bce9ca988d7d1e3f8ba"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UC9-y-6csu5WGm29I7JiwpnA"
title = "Computerphile"
site_url = "https://www.youtube.com/channel/UC9-y-6csu5WGm29I7JiwpnA"
body_hash = "3b20c1e35e84fcc590ac04240a4770c0f15b3535"
