identity = "8a205abbe0979715f4568a3f0101831225c64318"
resolved_url = "https://status.aws.amazon.com/rss/all.rss"
title = "Amazon Web Services Service Status"
site_url = "https://status.aws.amazon.com/"
language = "en-US"
etag = '"a2852d77f811d3f5ff50750f94c47ef9"'
last_modified = "Sun, 27 Sep 2026 19:29:16 GMT"
body_hash = "2aea69395f1f250a30448a0f9b8cc84b046162d4"
