identity = "c057b7fcb0b89992feb15fc5877d02ccf688fe78"
resolved_url = "https://eugeneyan.com/rss/"
title = "Eugene Yan"
site_url = "https://eugeneyan.com/"
etag = 'W/"6a3cb752-199df"'
last_modified = "Thu, 25 Jun 2026 05:06:26 GMT"
body_hash = "23dd37716d75dfddd2c7bfdf908c56a1d28248eb"
