identity = "e36b1b75567c65fa9d3ab6cd1ea682b275e1f939"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA"
title = "Fireship"
site_url = "https://www.youtube.com/channel/UCsBjURrPoezykLs9EqgamOA"
body_hash = "415ee81dbf6fdbeacd560e671f9fa6013701175c"
