identity = "e36b1b75567c65fa9d3ab6cd1ea682b275e1f939"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA"
title = "Fireship"
site_url = "https://www.youtube.com/channel/UCsBjURrPoezykLs9EqgamOA"
body_hash = "c547e1b8089bac9ae474d4a01e45b62d5095ef39"
