identity = "4937019e2c7962265008a2d5dd33634f56608900"
resolved_url = "https://simonwillison.net/atom/everything/"
title = "Simon Willison's Weblog"
site_url = "http://simonwillison.net/"
language = "en-US"
last_modified = "Wed, 07 Oct 2026 04:47:55 GMT"
body_hash = "da234f89298aa8070e77f55b0693d072c4dd7dfe"
