identity = "4937019e2c7962265008a2d5dd33634f56608900"
resolved_url = "https://simonwillison.net/atom/everything/"
title = "Simon Willison's Weblog"
site_url = "http://simonwillison.net/"
language = "en-US"
last_modified = "Tue, 06 Oct 2026 21:32:34 GMT"
body_hash = "6915fb4174c986cced2806a2ad965f6572bbbd6d"
