identity = "4937019e2c7962265008a2d5dd33634f56608900"
resolved_url = "https://simonwillison.net/atom/everything/"
title = "Simon Willison's Weblog"
site_url = "http://simonwillison.net/"
language = "en-US"
last_modified = "Sat, 03 Oct 2026 23:34:02 GMT"
body_hash = "f776e338c55611e77d629fb8290bb2677e93900c"
