identity = "101a0c89ad4c10d9f9068ea8977f62b2698ceccd"
resolved_url = "https://www.githubstatus.com/history.atom"
title = "GitHub Status - Incident History"
site_url = "https://www.githubstatus.com/"
language = "en-US"
etag = 'W/"80d87f183803a9a0497a033dee74211e"'
body_hash = "e95221ede07745decf8ef76c90be5fc2e5d5c332"
