identity = "101a0c89ad4c10d9f9068ea8977f62b2698ceccd"
resolved_url = "https://www.githubstatus.com/history.atom"
title = "GitHub Status - Incident History"
site_url = "https://www.githubstatus.com/"
language = "en-US"
etag = 'W/"0d6a7e72077288be1ac07ae578e223b9"'
body_hash = "3212633678bdba0c102d38e4ec820820b3782080"
