identity = "403c079f05c51c98d5519bf925ef2fd9ec737340"
resolved_url = "https://magazine.sebastianraschka.com/feed"
title = "Ahead of AI"
site_url = "https://magazine.sebastianraschka.com/"
language = "en"
etag = 'W/"2c317e-1YPboDZiAIdGRCA55bQd/Tz9jQg"'
body_hash = "d583dba03662008746442039e5b41dfd3cfd8d08"
