identity = "aff89fe15310dea5e16e04f564ed753900a2cc81"
resolved_url = "https://status.claude.com/history.atom"
title = "Claude Status - Incident History"
site_url = "https://status.claude.com/"
language = "en-US"
etag = 'W/"78fd1b08c33ade48247aae0725828d3e"'
body_hash = "e749de07d4a636916ccca9c65589760ead889776"
