identity = "43ad7a1d4bd3f4476a20a01577a11053ae0d06a9"
resolved_url = "https://www.latent.space/feed"
title = "Latent.Space"
site_url = "https://www.latent.space/"
language = "en"
etag = 'W/"152cdb-wsaM5pTEK7T0sxyAuiZYjaWqB7o"'
body_hash = "c2c68ce694c42bb4f4b31c80ba26588da5aa07ba"
