identity = "43ad7a1d4bd3f4476a20a01577a11053ae0d06a9"
resolved_url = "https://www.latent.space/feed"
title = "Latent.Space"
site_url = "https://www.latent.space/"
language = "en"
etag = 'W/"153d03-4dyLKiqn6036Aszip0pratIsH1Q"'
body_hash = "e1dc8b2a2aa7eb4dfa02cce2a74a6b6ad22c1f54"
