identity = "43ad7a1d4bd3f4476a20a01577a11053ae0d06a9"
resolved_url = "https://www.latent.space/feed"
title = "Latent.Space"
site_url = "https://www.latent.space/"
language = "en"
etag = 'W/"14d7b3-oDqLVbNKZJzVXz5TDn+mmX1KBEc"'
body_hash = "a03a8b55b34a649cd55f3e530e7fa6997d4a0447"
