identity = "f88811509dbdc6b1a52ebc059820830ce259e27e"
resolved_url = "https://mariozechner.at/rss.xml"
title = "{ Mario Zechner }"
site_url = "https://mariozechner.at/"
etag = 'W/"6a1bedd9-1c8d"'
last_modified = "Sunday, 27-Sep-2026 19:29:16 UTC"
body_hash = "5316a217b44e6f48de76c8e30f17ab3891ebd100"
