identity = "e16a629dc5fa9ae7b11d2c81684d4d9991a14ffc"
resolved_url = "https://ghuntley.com/rss/"
title = "Geoffrey Huntley"
site_url = "https://ghuntley.com/"
etag = 'W/"2da31-STA4b4sX2UGtzM7uLN7Q4jguKtw"'
body_hash = "4930386f8b17d941adccceee2cded0e2382e2adc"
