identity = "e16a629dc5fa9ae7b11d2c81684d4d9991a14ffc"
resolved_url = "https://ghuntley.com/rss/"
title = "Geoffrey Huntley"
site_url = "https://ghuntley.com/"
etag = 'W/"29633-Zv+DnF8VWSbl3QXrxtcelHIXYxs"'
body_hash = "66ff839c5f155926e5dd05ebc6d71e947217631b"
