identity = "e16a629dc5fa9ae7b11d2c81684d4d9991a14ffc"
resolved_url = "https://ghuntley.com/rss/"
title = "Geoffrey Huntley"
site_url = "https://ghuntley.com/"
etag = 'W/"3318d-FJBMGAM0Hcs11/z6VMaLaOO6SJ4"'
body_hash = "14904c1803341dcb35d7fcfa54c68b68e3ba489e"
