identity = "73453f38a06a0a851b5d767395e9bbde5dd7b535"
resolved_url = "https://harper.blog/index.xml"
title = "Home on Harper Reed's Blog"
site_url = "https://harper.blog/"
language = "en-US"
etag = '"e159e2c01de7e35031ea62a69b628da5-ssl-df"'
body_hash = "816895ef4d740258ea4e338c6b9465e6ae53bda9"
