identity = "098415ad8d02bc4f41564d3da243c5c8b88c4a12"
resolved_url = "https://lilianweng.github.io/index.xml"
title = "Lil'Log"
site_url = "https://lilianweng.github.io/"
language = "en-US"
etag = 'W/"6a55d3e4-13718"'
last_modified = "Tue, 14 Jul 2026 06:15:00 GMT"
body_hash = "1f1b87e95199541ec2572ea4121314436a25241f"
