identity = "a694d16ebca17231947891c5d59fd12fbddd2a12"
resolved_url = "https://www.thariq.io/rss.xml"
title = "Thariq Shihipar"
site_url = "https://example.me/"
body_hash = "453bb838045dddf04f7870c2852259d03bfceb87"
