identity = "9a67e7de01fe2a7eed3c49cdf4dda9d8ccb17755"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCSju5G2aFaWMqn-_0YBtq5A"
title = "Stand-up Maths"
site_url = "https://www.youtube.com/channel/UCSju5G2aFaWMqn-_0YBtq5A"
body_hash = "d9337fcd4fa7046ea9f099463b8c8b11a40ac847"
