identity = "7c5d4a84dd9fd904e86280a2bfc410afd2c7e3af"
resolved_url = "https://steipete.me/rss.xml"
title = "Peter Steinberger"
site_url = "https://steipete.me/"
etag = 'W/"edfe3c09bb50fe2ef81443c01323f39d"'
last_modified = "Sun, 27 Sep 2026 15:12:40 GMT"
body_hash = "eae3791d1be60d47c0a9dd5acc40935ba078a9d7"
