identity = "5f8802074b2cd8b27f08d5100d24d3d9d7510fc1"
resolved_url = "https://xkcd.com/atom.xml"
title = "xkcd.com"
site_url = "https://xkcd.com/"
language = "en"
etag = '"6ac04580-9c8"'
body_hash = "40b8b935d88db55dc692b95e735b5b34d4fbb6be"
