identity = "57dc1ceb454c08a08876d3e599d3ddf48c91f029"
resolved_url = "https://www.oneusefulthing.org/feed"
title = "One Useful Thing"
site_url = "https://www.oneusefulthing.org/"
language = "en"
etag = 'W/"de859-a4R0PTZX5kujVZ+KgtVeQDul2nk"'
body_hash = "6b84743d3657e64ba3559f8a82d55e403ba5da79"
